import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}
      <a href="https://wa.me/03442148252" target="_blank" className="whatsapp-icon">
  <img src="wsp.webp" alt="WhatsApp" />
</a>
      </body>
    </html>
  );
}
